### ISSUE TITLE
Error using the typescript sdk

### ISSUE THREAD

**Issue by davidmartinezros** [MagicTheGathering/mtg-sdk-typescript#3]
Hi,

I execute: 

`npm i mtg-sdk-ts --save`

Then I import the library:

`import * as Magic from "mtgsdk-ts";
`
And finally I execute a query example: 
`Magic.Cards.find("08618f8d5ebdc0c4d381ad11f0563dfebb21f4ee").then(result => console.log(result.name));`

And I get some errors on running:

> ERROR in ./node_modules/aws-sign2/index.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\aws-sign2'
> ERROR in ./node_modules/aws4/aws4.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\aws4'
> ERROR in ./node_modules/ecc-jsbn/index.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\ecc-jsbn'
> ERROR in ./node_modules/http-signature/lib/verify.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\http-signature\lib'
> ERROR in ./node_modules/http-signature/lib/signer.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\http-signature\lib'
> ERROR in ./node_modules/oauth-sign/index.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\oauth-sign'
> ERROR in ./node_modules/request/lib/helpers.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\request\lib'
> ERROR in ./node_modules/request/lib/hawk.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\request\lib'
> ERROR in ./node_modules/request/lib/oauth.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\request\lib'
> ERROR in ./node_modules/sshpk/lib/key.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/dhe.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/fingerprint.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/identity.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/utils.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/signature.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/private-key.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/certificate.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib\formats'
> ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib\formats'
> ERROR in ./node_modules/sshpk/lib/formats/pem.js
> Module not found: Error: Can't resolve 'crypto' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib\formats'
> ERROR in ./node_modules/request/lib/har.js
> Module not found: Error: Can't resolve 'fs' in 'C:\RepositoriGit\black-lotus\node_modules\request\lib'
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'http' in 'C:\RepositoriGit\black-lotus\node_modules\forever-agent'
> ERROR in ./node_modules/http-signature/lib/signer.js
> Module not found: Error: Can't resolve 'http' in 'C:\RepositoriGit\black-lotus\node_modules\http-signature\lib'
> ERROR in ./node_modules/request/request.js
> Module not found: Error: Can't resolve 'http' in 'C:\RepositoriGit\black-lotus\node_modules\request'
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'http' in 'C:\RepositoriGit\black-lotus\node_modules\tunnel-agent'
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'https' in 'C:\RepositoriGit\black-lotus\node_modules\forever-agent'
> ERROR in ./node_modules/request/request.js
> Module not found: Error: Can't resolve 'https' in 'C:\RepositoriGit\black-lotus\node_modules\request'
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'https' in 'C:\RepositoriGit\black-lotus\node_modules\tunnel-agent'
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'C:\RepositoriGit\black-lotus\node_modules\forever-agent'
> ERROR in ./node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in 'C:\RepositoriGit\black-lotus\node_modules\tough-cookie\lib'
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'C:\RepositoriGit\black-lotus\node_modules\tunnel-agent'
> ERROR in ./node_modules/request-promise/lib/rp.js
> Module not found: Error: Can't resolve 'os' in 'C:\RepositoriGit\black-lotus\node_modules\request-promise\lib'
> ERROR in ./node_modules/mime-types/index.js
> Module not found: Error: Can't resolve 'path' in 'C:\RepositoriGit\black-lotus\node_modules\mime-types'
> ERROR in ./node_modules/assert-plus/assert.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\assert-plus'
> ERROR in ./node_modules/combined-stream/lib/combined_stream.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\combined-stream\lib'
> ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\delayed-stream\lib'
> ERROR in ./node_modules/isstream/isstream.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\isstream'
> ERROR in ./node_modules/request/request.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\request'
> ERROR in ./node_modules/sshpk/lib/ed-compat.js
> Module not found: Error: Can't resolve 'stream' in 'C:\RepositoriGit\black-lotus\node_modules\sshpk\lib'
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'C:\RepositoriGit\black-lotus\node_modules\forever-agent'
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'C:\RepositoriGit\black-lotus\node_modules\tunnel-agent'
> ERROR in ./node_modules/request/request.js
> Module not found: Error: Can't resolve 'zlib' in 'C:\RepositoriGit\black-lotus\node_modules\request'
> i ï½¢wdmï½£: Failed to compile.

Do you know how to solve it?

Thanks,

David

**Comment by Yuudaari** [comment]
I can't reproduce this. I'm going to guess your problem is unrelated to the module.

**Comment by davidmartinezros** [comment]
I'm using Angular 7 and Angular-Cli.

Perhaps the problem comes with Angular-Cli?

**Comment by davidmartinezros** [comment]
I found the solution:

You have to replace
node: false,
for:
node: { crypto: true, stream: true, fs: "empty", net: "empty", tls: "empty" },
in the file: `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js'

**Comment by aserrno** [comment]
Perfect! @davidmartinezros  Thank you
